### ISSUE TITLE
Add variables for custom repo

### ISSUE THREAD

**Issue by felixPG** [infinityworks/docker-hub-exporter#10]
Hi:

Its possible to make **baseURL** as a parameter instead of a variable to use a custom v2 repo and not dockerhub?

Regards

**Comment by tianon** [comment]
With how the exporter works, this isn't really possible -- it uses the Docker Hub API, not the registry API (which is what Docker uses when pulling images), especially so it can grab metadata that isn't part of the normal (documented) registry API like number of pulls, stars, etc.

**Comment by Rucknar** [comment]
Closing as per above comment. Open to a PR though to add support in the future.
