### ISSUE TITLE
Docker Hub automated build broken

### ISSUE THREAD

**Issue by solidnerd** [infinityworks/docker-hub-exporter#8]
Hey,

nice project finally written in Go ;).  Sadly your Docker Hub Image is broken.

![image](https://user-images.githubusercontent.com/886383/27214499-202891c8-526d-11e7-894a-dc3bc7ac000c.png)

I think you can fix it.

**Comment by Rucknar** [comment]
Thanks for the heads up, looks to be because the Dockerfile is using multi-stage builds, something the hub doesn't yet support. I've done the build locally and pushed up, i'll leave this open and try figure out when hub will support multi-stage builds.

**Comment by Rucknar** [comment]
Builds now done through Docker Cloud for the multi-stage build support.

**Comment by Rucknar** [comment]
THough... I don't know how that can be publically viewed.. i'll take a look at making it clearer.
